### canny边缘检测

In [1]:
import cv2 
import numpy as np


# 导入图片
img = cv2.imread('./lena.png')

# 阈值给的稍大一些, 绘制的边缘不够精细
lena1 = cv2.Canny(img, 100, 200)

# 可以通过给小一点阈值, 得到较为精细的边缘
lena2 = cv2.Canny(img, 64, 128)

lena3 = cv2.Canny(img, 80, 150)
cv2.imshow('lena', np.hstack((lena1, lena2, lena3)))

cv2.waitKey(0)
cv2.destroyAllWindows()

### 全局二值化


In [10]:
import cv2 
import numpy as np


# 导入图片
img = cv2.imread('./dog.jpeg')

# 二值化操作是对灰度图像操作, 把dog变成灰度图像
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

# 注意, threshold会返回两个值, 一个是阈值, 二值化处理后的图片
thresh, dst = cv2.threshold(gray, 110, 255, cv2.THRESH_BINARY)

print(thresh)
# 展示
cv2.imshow('dog', np.hstack((gray, dst)))
cv2.waitKey(0)
cv2.destroyAllWindows()

110.0


### 自适应阈值二值化

In [2]:
import cv2 
import numpy as np


# 导入图片
img = cv2.imread('./dog.jpeg')

# 二值化操作是对灰度图像操作, 把dog变成灰度图像
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

# 自适应阈值二值化只有一个返回值,
dst = cv2.adaptiveThreshold(gray, 255, cv2.ADAPTIVE_THRESH_GAUSSIAN_C, cv2.THRESH_BINARY, 19, 0)

# 展示
cv2.imshow('dog', np.hstack((gray, dst)))
cv2.waitKey(0)
cv2.destroyAllWindows()

In [3]:
# 更加具有代表性的例子
import cv2 
import numpy as np


# 导入图片
img = cv2.imread('./math.png')

# 创建窗口调整显示的大小
cv2.namedWindow('img', cv2.WINDOW_NORMAL)
cv2.resizeWindow('img', 640, 480)

# 二值化操作是对灰度图像操作, 把dog变成灰度图像
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

# 我们发现适应全局阈值二值化, 对图片光线不好的地方效果不太好
thresh, dst = cv2.threshold(gray, 180, 255, cv2.THRESH_BINARY)

print(thresh)
# 展示
cv2.imshow('img', np.hstack((gray, dst)))
cv2.waitKey(0)
cv2.destroyAllWindows()

180.0


In [4]:
# 使用自适应阈值二值化
# 更加具有代表性的例子
import cv2 
import numpy as np


# 导入图片
img = cv2.imread('./math.png')

# 创建窗口调整显示的大小
cv2.namedWindow('img', cv2.WINDOW_NORMAL)
cv2.resizeWindow('img', 1080, 720)

# 二值化操作是对灰度图像操作, 把dog变成灰度图像
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

# 我们发现适应全局阈值二值化, 对图片光线不好的地方效果不太好
dst = cv2.adaptiveThreshold(gray, 255, cv2.ADAPTIVE_THRESH_GAUSSIAN_C, cv2.THRESH_BINARY_INV, 5, 0)

print(thresh)
# 展示
cv2.imshow('img', np.hstack((gray, dst)))
cv2.waitKey(0)
cv2.destroyAllWindows()

180.0


### 腐蚀操作

In [7]:
import cv2 
import numpy as np


# 导入图片
img = cv2.imread('./j.png')

# 定义核
kernel = np.ones((5, 5), np.uint8)
dst = cv2.erode(img, kernel, iterations=2)

cv2.imshow('img', np.hstack((img, dst)))

cv2.waitKey(0)
cv2.destroyAllWindows()

### 获取形态学卷积核

In [6]:
import cv2 
import numpy as np

img = cv2.imread('./j.png')

kernel = cv2.getStructuringElement(cv2.MORPH_ELLIPSE, (5, 5))
print(kernel)

# 腐蚀
dst = cv2.erode(img, kernel)

cv2.imshow('img', np.hstack((img, dst)))

cv2.waitKey(0)
cv2.destroyAllWindows()

[[0 0 1 0 0]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [0 0 1 0 0]]


### 膨胀操作


In [40]:
import cv2 
import numpy as np

img = cv2.imread('./j.png')

kernel = cv2.getStructuringElement(cv2.MORPH_RECT, (5, 5))

# 膨胀
dst = cv2.dilate(img, kernel, iterations=1)

cv2.imshow('img', np.hstack((img, dst)))

cv2.waitKey(0)
cv2.destroyAllWindows()

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [42]:
# 膨胀和腐蚀简单应用
import cv2 
import numpy as np


# 导入图片
img = cv2.imread('./msb.png')

# 定义核
kernel = np.ones((5, 5), np.uint8)
# 先腐蚀
dst = cv2.erode(img, kernel, iterations=1)

# 再膨胀
dst = cv2.dilate(dst, kernel, iterations=1)
cv2.imshow('img', np.hstack((img, dst)))

cv2.waitKey(0)
cv2.destroyAllWindows()