In [1]:
import cv2


dog = cv2.imread('./dog.jpeg')
cv2.imshow('dog', dog)

cv2.waitKey(0)
cv2.destoryAllWindows()

AttributeError: module 'cv2.cv2' has no attribute 'destoryAllWindows'

In [2]:
# 想看dog中有多少种不同的颜色.
dog

array([[[213, 175, 140],
        [216, 176, 141],
        [220, 178, 143],
        ...,
        [223, 191, 156],
        [224, 192, 157],
        [225, 190, 156]],

       [[222, 180, 145],
        [222, 180, 145],
        [220, 178, 143],
        ...,
        [227, 195, 160],
        [227, 195, 160],
        [225, 193, 157]],

       [[225, 180, 146],
        [225, 180, 146],
        [223, 181, 146],
        ...,
        [227, 195, 160],
        [225, 193, 158],
        [222, 190, 154]],

       ...,

       [[ 50,  46,  28],
        [ 54,  47,  30],
        [ 55,  48,  33],
        ...,
        [ 95, 155, 209],
        [ 92, 149, 204],
        [103, 160, 215]],

       [[ 58,  49,  29],
        [ 59,  49,  31],
        [ 63,  50,  34],
        ...,
        [ 94, 151, 206],
        [100, 157, 212],
        [100, 157, 213]],

       [[ 67,  56,  36],
        [ 73,  59,  41],
        [ 71,  55,  39],
        ...,
        [ 73, 130, 185],
        [113, 170, 226],
        [ 81, 138, 194]]

In [3]:
from pandas import DataFrame

In [4]:
# 用每一个像素创建dataframe
df = DataFrame(dog.reshape(-1, 3))

In [5]:
df.head()

0    1    2
0  213  175  140
1  216  176  141
2  220  178  143
3  221  179  144
4  217  177  142

In [9]:
df.shape

(179640, 3)

In [10]:
# dog中不重复的颜色
179640 - df.duplicated().sum()

54242

In [11]:
print(cv2.COLOR_BGR2RGBA)

2


In [13]:
# 关键API cv2.cvtColor
import cv2


def callback(value):
    pass


cv2.namedWindow('color', cv2.WINDOW_NORMAL)
cv2.resizeWindow('color', 640, 480)

# 读取照片, OpenCV读进来的图片默认是BGR的色彩空间.
img = cv2.imread('./cat.jpeg')

# 定义颜色空间转化列表
color_spaces = [
    # 所有颜色空间的转化都是COLOR开头
    cv2.COLOR_BGR2RGBA, cv2.COLOR_BGR2BGRA,
    cv2.COLOR_BGR2GRAY, cv2.COLOR_BGR2HSV,
    cv2.COLOR_BGR2YUV
]

# 设置trackbar
cv2.createTrackbar('trackbar', 'color', 0, 4, callback)

while True:
    # 获取trarckbar的值
    index =cv2.getTrackbarPos('trackbar', 'color')
    
    # 进行颜色空间转换
    cvt_img = cv2.cvtColor(img, color_spaces[index])
    
    cv2.imshow('color', cvt_img)
    key = cv2.waitKey(10)
    if key == ord('q'):
        break
    
cv2.destroyAllWindows()

In [ ]:
# opencv用mat这种数据结构来表示图片的. 
# C++中是用mat来保存图片. python中把mat转化成了numpy的ndarray
cv2.imshow()

In [16]:
type(img)

numpy.ndarray

In [17]:
img.channels

AttributeError: 'numpy.ndarray' object has no attribute 'channels'

In [20]:
# ndarray4种常见属性?
img.data

In [23]:
import numpy as np

ones = np.ones((2, 3))

In [24]:
ones.data

In [25]:
# 元素的总个数
img.size

921600

In [26]:
img.dtype

dtype('uint8')

In [27]:
img.shape

(480, 640, 3)

In [28]:
img.itemsize

1

In [29]:
img.ndim

3

In [30]:
img.imag

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       ...,

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]], dtype=uint8)

In [33]:
# 因为python中图片数据已经包装成ndarray了, 所以对mat的深浅拷贝,其实就是对ndarray深浅拷贝.
import cv2
import numpy as np

img = cv2.imread('./cat.jpeg')

# 浅拷贝.
img2 = img.view()

# 深拷贝
img3 = img.copy()

img[10:100, 10: 100] = [0, 0, 255]

cv2.imshow('img', np.vstack((img, img2, img3)))

cv2.waitKey(0)
cv2.destroyAllWindows()

In [37]:
# 图像的分割与融合
import cv2
import numpy as np

img = np.zeros((200, 200, 3), np.uint8)

# 分割通道
b, g, r = cv2.split(img)
print('b:', b)
# 修改一些颜色
b[10:100, 10:100] = 255
g[10:100, 10: 100] = 255

# 合并通道
img2 = cv2.merge((b, g, r))

cv2.imshow('img', np.hstack((b, g)))
cv2.imshow('img2', np.hstack((img, img2)))

cv2.waitKey(0)
cv2.destroyAllWindows()

b: [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [45]:
# 绘制各种图形
import cv2
import numpy as np


# 创建纯黑的背景图用来画图形
img = np.zeros((800, 800, 3), np.uint8)
# line(img, pt1, pt2, color, thickness, lineType, shift)
cv2.line(img, (10, 20), (300, 400), (0, 0, 255), 5, 4)
# cv2.line(img, (80, 100), (380, 480), (0, 0, 255), 5, 16)#
# 和画线是完全一样的.
# cv2.rectangle(img, (80, 100), (380, 380), (0, 255, 0), 5)

# 画圆 需要传圆心坐标, 半径大小
# cv2.circle(img, (320, 240), 100, (0, 0, 255), 5, 16)

# ellipse(img, 中心点, 长宽的一半, 角度, 从哪个角度开始, 从哪个角度结束,...)
# axes ->axis
# cv2.ellipse(img, (320, 240), (100, 100), 0, 0, 360, [0, 0, 255], 5, 16)
# 绘制多边形
# pts多边形的点集, 必须是int32位
pts = np.array([(250, 100), (150, 300), (50, 280)], np.int32)
# 注意pts是3维的. 
# cv2.polylines(img, [pts], False, (0, 0, 255), 5)

# 填充多边形
# cv2.fillPoly(img, [pts], (0, 0, 255))
# cv2.fillConvexPoly()
# 绘制文本
cv2.putText(img, '你好,我好, 大家好', (50, 400), cv2.FONT_HERSHEY_COMPLEX, 2, [0, 0, 255])

cv2.imshow('draw', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [46]:
# 使用OpenCV绘制中文.
# 曲线救国, OpenCV是没有办法直接绘制中文. 
# 使用Pillow包.  需要安装 pip install pillow 
from PIL import ImageFont, ImageDraw, Image


# 纯白
# img = np.full((500, 500, 3), fill_value=255, dtype=np.uint8)
img = cv2.imread('./cat.jpeg')

# 导入字体文件
font = ImageFont.truetype('./msyhbd.ttc', 35)

# 创建一个pillow的图片
img_pil = Image.fromarray(img)

draw = ImageDraw.Draw(img_pil)
# 利用draw去绘制中文
draw.text((100, 250), '你好, 我好, 大家好', font=font, fill=(0, 255, 0, 0))

# 重新变回ndarray
img = np.array(img_pil)

cv2.imshow('img' ,img)

cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
cv2.FONT

In [3]:
import cv2
import numpy as np

img = cv2.imread('./cat.jpeg')

# 浅拷贝
temp = img[0:100, 0:100]
# 深拷贝
temp2 = img[0:100, 0:100].copy()

print(temp)
temp[:] = [0, 0, 255]
temp2[:] = [0, 255, 0]
cv2.imshow('temp', temp)
cv2.imshow('temp2', temp2)
cv2.imshow('img', img)

cv2.waitKey(0)
cv2.destroyAllWindows()

[[[204 203 205]
  [205 204 206]
  [206 205 207]
  ...
  [209 208 210]
  [209 208 210]
  [210 209 211]]

 [[204 203 205]
  [205 204 206]
  [206 205 207]
  ...
  [209 208 210]
  [209 208 210]
  [210 209 211]]

 [[204 203 205]
  [204 203 205]
  [205 204 206]
  ...
  [208 207 209]
  [209 208 210]
  [209 208 210]]

 ...

 [[202 201 203]
  [202 201 203]
  [202 201 203]
  ...
  [203 205 206]
  [203 205 206]
  [203 205 206]]

 [[202 201 203]
  [202 201 203]
  [202 201 203]
  ...
  [203 205 206]
  [203 205 206]
  [203 205 206]]

 [[202 201 203]
  [202 201 203]
  [202 201 203]
  ...
  [203 205 206]
  [203 205 206]
  [203 205 206]]]


In [38]:
# 弑神同学作业代码
import cv2
import numpy as np
import math

ix,iy = -1,-1
mode = 0  

def draw(event, x, y, flag, userdata):
    global ix, iy
    if mode == 1:
        if event == cv2.EVENT_LBUTTONDOWN:
            ix,iy = x,y
        elif event == cv2.EVENT_LBUTTONUP and (flag & cv2.EVENT_FLAG_LBUTTON):
            cv2.line(img, (ix, iy), (x, y), (0, 0, 255), 1, 4)
            cv2.imshow('mouse', img)
        elif event == cv2.EVENT_LBUTTONUP:
            cv2.line(img, (ix, iy), (x, y), (0, 0, 255), 1, 4)
            cv2.imshow('mouse', img)
    if mode == 2:
        if event == cv2.EVENT_LBUTTONDOWN:
            ix,iy = x,y
        elif event == cv2.EVENT_LBUTTONUP and (flag & cv2.EVENT_FLAG_LBUTTON):
            cv2.rectangle(img, (ix, iy), (x, y), (0, 0, 255), 1, 4)
            cv2.imshow('mouse', img)
        elif event == cv2.EVENT_LBUTTONUP:
            cv2.rectangle(img, (ix, iy), (x, y), (0, 0, 255), 1, 4)
            cv2.imshow('mouse', img)
    if mode == 3:
        if event == cv2.EVENT_LBUTTONDOWN:
            ix,iy = x,y
        elif event == cv2.EVENT_LBUTTONUP and (flag & cv2.EVENT_FLAG_LBUTTON):
            cv2.circle(img, (ix, iy), int(np.sqrt((ix-x)**2+(iy-y)**2)), (0, 0, 255), 1, 4)
            cv2.imshow('mouse', img)
        elif event == cv2.EVENT_LBUTTONUP:
            cv2.circle(img, (ix, iy), int(np.sqrt((ix-x)**2+(iy-y)**2)), (0, 0, 255), 1, 4)
            cv2.imshow('mouse', img)
        
cv2.namedWindow('mouse', cv2.WINDOW_NORMAL)

cv2.resizeWindow('mouse', 640, 360)

cv2.setMouseCallback('mouse', draw,0)

img = np.zeros((360, 640, 3), np.uint8)

img.fill(255)

while True:
    cv2.imshow('mouse', img)
    key = cv2.waitKey(0)
    if key == ord('l'):
        mode = 1
    elif key == ord('r'):
        mode = 2
    elif key == ord('c'):
        mode = 3
    elif key == ord('q'):
        break
    
cv2.destroyAllWindows()

In [39]:
# swain同学代码
import numpy as np
import cv2 as cv

ix,iy = -1,-1
drawing=False
def draw_line(event,x,y,flags,param):
    global ix,iy,drawing#全局初始化
    if event==cv2.EVENT_LBUTTONDOWN:
        drawing=True#正在绘制
        ix,iy=x,y#按下时，决定划线的起始位置
    elif event==cv2.EVENT_LBUTTONUP:
            if drawing==True:
                    cv2.line(img,(ix,iy),(x,y),(0,255,158),4)#松开时为画直线的末端位置
def  draw_circle(event,x,y,flags,param):
    global ix,iy,drawing
    if event==cv2.EVENT_LBUTTONDOWN:
        drawing=True
        ix,iy=x,y
    elif event==cv2.EVENT_LBUTTONUP:
            if drawing==True:
                    r=int(np.sqrt((x-ix)**2+(y-iy)**2))#逆向求半径 R只能为int
                    cv2.circle(img,(ix,iy),r,(0,255,50),-1)
def   draw_rectangle(event,x,y,flags,param):
    global ix,iy,drawing
    if event==cv2.EVENT_LBUTTONDOWN:
        drawing=True
        ix,iy=x,y
    elif event==cv2.EVENT_LBUTTONUP:
            if drawing==True:
                    cv2.rectangle(img,(ix,iy),(x,y),(0,255,200),-1)   
while True:
    cv2.imshow('image',img)
    k=cv2.waitKey(1)
    if k==ord('l'):#按下L键 为画直线
        cv2.setMouseCallback('image',draw_line) 
    elif k==ord('c'):# 按下C键为画圆
        cv2.setMouseCallback('image',draw_circle)
    elif k==ord('r'):#按下R键为画矩形
        cv2.setMouseCallback('image',draw_rectangle)
    elif k== ord('q'):
        break
cv2.destroyAllWindows()

In [ ]:
# 作业思路:
# 按下按键比如l, 进入绘制直线模式. 需要记录起始位置, 即按下鼠标左键的那一瞬间的坐标位置.
# 左键起来的鼠标坐标作为终点. 然后绘制.

In [47]:
# 按下l, 拖动鼠标, 可以绘制直线.
# 按下r, 拖到鼠标, 可以绘制矩形
# 按下c, 拖动鼠标, 可以绘制圆. 拖动的长度可以作为半径.
import cv2
import numpy as np

# 这是一个全局标志, 判断要画什么类型的图.
curshape = 0
startpos = (0, 0)

# 创建背景图
img = np.zeros((480, 640, 3), np.uint8)

# 要监听鼠标的行为, 所以必须通过鼠标回调函数实现.
def mouse_callback(event, x, y, flags, userdata):
    # 引入全局变量
    global curshape, startpos
    # 引入非本层的局部变量用什么关键字nonlocal
    if event == cv2.EVENT_LBUTTONDOWN:
        # 记录起始位置
        startpos = (x, y)
    elif event == cv2.EVENT_LBUTTONUP:
        # 判断要画什么类型的图.
        if curshape == 0: # 画直线
            cv2.line(img, startpos, (x, y), (0, 0, 255), 3)
        elif curshape == 1: # 画矩形
            cv2.rectangle(img, startpos, (x, y), (0, 0, 255), 3)
        elif curshape == 2: # 画圆
            # 注意计算半径
            a = (x - startpos[0])
            b = (y - startpos[1])
            r = int((a ** 2 + b ** 2) ** 0.5)
            # 画圆的时候, 半径必须是整数
            cv2.circle(img, startpos, r, (0, 0, 255), 3)
        else: # 按其他的按键
            print('暂不支持绘制其他图形')
            
            
# 创建窗口
cv2.namedWindow('drawshape', cv2.WINDOW_NORMAL)
# 设置鼠标回调函数
cv2.setMouseCallback('drawshape', mouse_callback)

while True:
    cv2.imshow('drawshape', img)
    # 检测按键
    key = cv2.waitKey(1)
    if key == ord('q'):
        break
    elif key == ord('l'):
        curshape = 0
    elif key == ord('r'):
        curshape = 1
    elif key == ord('c'):
        curshape = 2
        
cv2.destroyAllWindows()

In [52]:
# 按下l, 拖动鼠标, 可以绘制直线.
# 按下r, 拖到鼠标, 可以绘制矩形
# 按下c, 拖动鼠标, 可以绘制圆. 拖动的长度可以作为半径.
import cv2
import numpy as np

# 这是一个全局标志, 判断要画什么类型的图.
curshape = 0
startpos = (0, 0)

# 创建背景图
img = np.zeros((480, 640, 3), np.uint8)

# 要监听鼠标的行为, 所以必须通过鼠标回调函数实现.
def mouse_callback(event, x, y, flags, userdata):
    # 引入全局变量
    global curshape, startpos
    # 引入非本层的局部变量用什么关键字nonlocal
    if event == cv2.EVENT_LBUTTONDOWN:
        # 记录起始位置
        startpos = (x, y)
        
    elif event ==0 and flags == 1: # 表示按下鼠标左键并移动鼠标
        if curshape == 0: # 画直线
            cv2.line(img, startpos, (x, y), (0, 0, 255), 1)
        elif curshape == 1: # 画矩形
            cv2.rectangle(img, startpos, (x, y), (0, 0, 255), 1)
        elif curshape == 2: # 画圆
            # 注意计算半径
            a = (x - startpos[0])
            b = (y - startpos[1])
            r = int((a ** 2 + b ** 2) ** 0.5)
            # 画圆的时候, 半径必须是整数
            cv2.circle(img, startpos, r, (0, 0, 255), 1)
        else: # 按其他的按键
            print('暂不支持绘制其他图形')
            
    elif event == cv2.EVENT_LBUTTONUP:
        # 判断要画什么类型的图.
        if curshape == 0: # 画直线
            cv2.line(img, startpos, (x, y), (0, 0, 255), 3)
        elif curshape == 1: # 画矩形
            cv2.rectangle(img, startpos, (x, y), (0, 0, 255), 1)
        elif curshape == 2: # 画圆
            # 注意计算半径
            a = (x - startpos[0])
            b = (y - startpos[1])
            r = int((a ** 2 + b ** 2) ** 0.5)
            # 画圆的时候, 半径必须是整数
            cv2.circle(img, startpos, r, (0, 0, 255), 1)
        else: # 按其他的按键
            print('暂不支持绘制其他图形')
            
            
# 创建窗口
cv2.namedWindow('drawshape', cv2.WINDOW_NORMAL)
# 设置鼠标回调函数
cv2.setMouseCallback('drawshape', mouse_callback)

while True:
    cv2.imshow('drawshape', img)
    # 检测按键
    key = cv2.waitKey(1)
    if key == ord('q'):
        break
    elif key == ord('l'):
        curshape = 0
    elif key == ord('r'):
        curshape = 1
    elif key == ord('c'):
        curshape = 2
        
cv2.destroyAllWindows()